# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-02 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcribers',
            new_name='Subcriber',
        ),
    ]
